### ISSUE TITLE
Docker setup

### ISSUE THREAD

**Issue by lovegandhi** [HASKADOG/address_keeper#2]
Can you work through your docker setup and make it usable to another developer? I am reviewing your take-home project and found that there are numerous issues that prevent the app from being usable. Also, please provide a user:password to be used during the login process.

**Comment by HASKADOG** [comment]
Hi, @lovegandhi ! Sure! What problem did you face? This? https://sentry.io/organizations/to-the-moon-a3/issues/3470111777/?query=is%3Aunresolved
ramazan.testsafiiulin@yahoo.com:LeeerojJenkins123 (sentry creds)

**Comment by HASKADOG** [comment]
@lovegandhi I've got what you mean. Fixing

**Comment by HASKADOG** [comment]
@lovegandhi Done! I hope I fixed the mistakes you faced. I also added a simple design, please take a look at it
